### ISSUE TITLE
Set default profile picture to something weird

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/clippy#14]
Inspired by the anonymous Google Docs animals. Some weird animal photos?

**Comment by MatthewStanciu** [comment]
Hell yeah. This is pretty easy, I think I can get to it tonight

**Comment by lachlanjc** [comment]
@MatthewStanciu Is this on the plate still?

**Comment by MatthewStanciu** [comment]
Eventually, but probably not before launch

**Comment by MatthewStanciu** [comment]
Closing because I'm pretty sure this isn't possible :(
