### ISSUE TITLE
Clippy currently does not give new users GP

### ISSUE THREAD

**Issue by hkatzdev** [hackclub/clippy#3]
Since Clippy has no GP the current Banker API will not work. Clippy either needs a large amount of GP or a different way to change the airtable.

**Comment by MatthewStanciu** [comment]
Ohhh, that's why it's not working. I thought @neelr gave Clippy infinite GP?

**Comment by MatthewStanciu** [comment]
I think I'm just going to remove the whole GP part of the tutorial for now

**Comment by MatthewStanciu** [comment]
Ok Neel just gave Clippy infinite GP, but I'm actually going to remove the GP part of the tutorial for now until there's a real use for GP
